version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
